# Site settings
baseURL = "https://wallby.nl"
languageCode = "en-us"
title = "Maarten ten Velden"
theme = "forty"
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["taxonomy", "section"]

# https://www.cloudhadoop.com/hugo-raw-html-committed/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Provide your metadata here.
  name = "Maarten ten Velden"
  description = "Creative Engineer"

  # Link custom assets relative to /static
  custom_css = ["css/main_overrides.css"]
  custom_js  = []

  # Just a custom image variable, please define it in .md files for content.
  image = ""
  
  # Technologies
  [[params.technologies]]
    name = "Unity"
    url = "https://unity3d.com/"
    image = "/img/unity.png"
    
  [[params.technologies]]
    name = "Unreal Engine"
    url = "https://www.unrealengine.com/en-US/blog"
    image = "/img/unreal_engine.png"

  [[params.technologies]]
    name = "Visual Studio"
    url = "https://www.visualstudio.com/"
    image = "/img/visual_studio.svg"

  [[params.technologies]]
    name = "Eclipse IDE"
    url = "https://www.eclipse.org/eclipseide/"
    image = "/img/eclipse.png"
  
  [[params.technologies]]
    name = "Make"
    url = "https://www.gnu.org/software/make/"
    image = "/img/make.png"
  
  [[params.technologies]]
    name = "HacknPlan"
    url = "https://www.hacknplan.com/"
    image = "/img/hacknplan.png"

  [[params.technologies]]
    name = "Jira"
    url = "https://www.jira.com/"
    image = "/img/jira.png"
    
  [[params.technologies]]
    name = "Git"
    url = "https://www.git-scm.com/"
    image = "/img/git.png"

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Maarten"
    # subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Contact"
      url = "page/contact"

    [[params.navigation.links]]
      name = "About me"
      url = "page/about"

    #[[params.navigation.button2]]
    #  name = ""
    #  url = ""

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Maarten"
    subtitle = "game developer"
    buttonText = "Read more"

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "arguments-mini"
      subtitle = "A library for parsing commandline arguments written in C++"
      image = "arguments-mini.jpg"
      url = "project/arguments_mini"

    [[params.tiles.showcase]]
      title = "Project Sulphur"
      subtitle = "A custom engine for Windows and PS4 written in C++"
      image = "project_sulphur.jpg"
      url = "project/project_sulphur"

    [[params.tiles.showcase]]
      title = "AGR"
      subtitle = "An anti-grav racer built in a custom engine for Windows and PS4 written in C++"
      image = "agr.jpg"
      url = "project/agr"

    [[params.tiles.showcase]]
      title = "Mayor"
      subtitle = "An atmospheric city management game made in two and a half weeks"
      image = "mayor.jpg"
      url = "project/mayor"

    [[params.tiles.showcase]]
      title = "Halo Hunters"
      subtitle = "A fast-paced shooter made in two weeks"
      image = "halo_hunters.jpg"
      url = "project/halo_hunters"

    [[params.tiles.showcase]]
      title = "BaRock Battles"
      subtitle = "A party game made for the Global Jam of 2016"
      image = "barock_battles.jpg"
      url = "project/barock_battles"

    [[params.tiles.showcase]]
      title = "Jellyventure"
      subtitle = "A game with the theme jelly written in C++ using SDL2"
      image = "jellyventure.jpg"
      url = "project/jellyventure"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "f/xoqyzlbg"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Maarten ten velden"

    [[params.footer.social]]
      icon = "fa-envelope"
      url= "mailto:info@wallby.nl"
      label = "Email"
      
    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/maarten-ten-velden/"
      label = "LinkedIn"
            
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/Wallby"
      label = "GitHub"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
