# Site settings
baseURL = "https://wallby.nl"
languageCode = "en-us"
title = "Maarten ten Velden"
theme = "forty"
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["taxonomy"]

# https://www.cloudhadoop.com/hugo-raw-html-committed/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Provide your metadata here.
  name = "Maarten ten Velden"
  description = "Game developer"

  # Link custom assets relative to /static
  custom_css = ["css/main_overrides.css"]
  custom_js  = []

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # Technologies
  [[params.technologies]]
    name = "Supercollider"
    url = "https://supercollider.github.io/"
    image = "/img/supercollider.svg"
    smooth_image = true

  [[params.technologies]]
    name = "Unity"
    url = "https://unity3d.com/"
    image = "/img/unity.png"
    smooth_image = true

  [[params.technologies]]
    name = "Unreal Engine"
    url = "https://www.unrealengine.com/en-US/blog"
    image = "/img/unreal_engine.png"
    smooth_image = true

  [[params.technologies]]
    name = "Visual Studio"
    url = "https://www.visualstudio.com/"
    image = "/img/visual_studio.svg"

  [[params.technologies]]
    name = "CMake"
    url = "https://cmake.org/"
    image = "/img/cmake.svg"
    smooth_image = true

  [[params.technologies]]
    name = "Make"
    url = "https://www.gnu.org/software/make/"
    image = "/img/make.png"
    smooth_image = true

  [[params.technologies]]
    name = "Batch"
    url = "https://en.wikipedia.org/wiki/Batch_file"
    image = "/img/batch.png"
    smooth_image = true

  [[params.technologies]]
    name = "Powershell"
    url = "https://learn.microsoft.com/en-gb/powershell/"
    image = "/img/powershell.png"
    smooth_image = true

  [[params.technologies]]
    name = "Bourne shell"
    url = "https://en.wikipedia.org/wiki/Bourne_shell"
    image = "/img/bourne_shell.png"
    smooth_image = true
    last_in_column = true

  [[params.technologies]]
    name = "Excel"
    url = "https://support.microsoft.com/en-us/office/download-and-install-or-reinstall-office-2019-office-2016-or-office-2013-7c695b06-6d1a-4917-809c-98ce43f86479"
    image = "/img/excel.svg"

  [[params.technologies]]
    name = "Audacity"
    url = "https://www.audacityteam.org/"
    image = "/img/audacity.svg"
    smooth_image = true

  [[params.technologies]]
    name = "Jira"
    url = "https://www.jira.com/"
    image = "/img/jira.png"
    smooth_image = true

  [[params.technologies]]
    name = "Trello"
    url = "https://trello.com/"
    image = "/img/trello.png"
    smooth_image = true

  [[params.technologies]]
    name = "HacknPlan"
    url = "https://www.hacknplan.com/"
    image = "/img/hacknplan.png"
    smooth_image = true

  [[params.technologies]]
    name = "Git"
    url = "https://www.git-scm.com/"
    image = "/img/git.png"
    smooth_image = true

  [[params.technologies]]
    name = "Perforce"
    url = "https://www.perforce.com/downloads/helix-visual-client-p4v"
    image = "/img/perforce.png"
    smooth_image = true
    last_in_column = true

  [[params.technologies]]
    name = "ChromeOS"
    url = "https://chromeos.google/products/chromeos-flex/"
    image = "/img/chrome.svg"
    smooth_image = false

  [[params.technologies]]
    name = "PS4"
    url = "https://en.wikipedia.org/wiki/PlayStation_4_system_software#System"
    image = "/img/ps4.png"
    smooth_image = true

  [[params.technologies]]
    name = "Vulkan"
    url = "https://www.vulkan.org/"
    image = "/img/vulkan.png"
    smooth_image = true

  [[params.technologies]]
    name = "DirectX 11"
    url = "https://en.wikipedia.org/wiki/DirectX"
    image = "/img/directx.png"
    smooth_image = true

  [[params.technologies]]
    name = "DirectX 12"
    url = "https://en.wikipedia.org/wiki/DirectX"
    image = "/img/directx.png"
    smooth_image = true

  [[params.technologies]]
    name = "Win32"
    url = "https://learn.microsoft.com/en-us/windows/win32/apiindex/windows-api-list"
    image = "/img/microsoft.ico"
    smooth_image = false

  [[params.technologies]]
    name = "Xlib"
    url = "https://x.org/releases/current/doc/libX11/libX11/libX11.html"
    image = "/img/xlib.ico"
    smooth_image = false

  [[params.technologies]]
    name = "SDL"
    url = "https://www.libsdl.org/"
    image = "/img/sdl.png"
    smooth_image = true

  [[params.other_technologies]]
    name = "Redstone"
    image = "/img/redstone.webp"
    smooth_image = false
  
  [[params.other_technologies]]
    name = "Portaudio"
    url = "https://www.portaudio.com/"
    image = "/img/portaudio.png"
    smooth_image = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Maarten"
    # subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"
    
    [[params.navigation.projecttypes]]
      name = "School"
      url = "school_project"
    [[params.navigation.projecttypes]]
      name = "Personal"
      url = "personal_project"

    [[params.navigation.links]]
      name = "Home"
      url = ""

    [[params.navigation.links]]
      name = "Contact"
      url = "page/contact"

    [[params.navigation.links]]
      name = "About me"
      url = "page/about"

    #[[params.navigation.button1]]
    #  name = ""
    #  url = ""
    
    #[[params.navigation.button2]]
    #  name = ""
    #  url = ""

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Maarten"
    subtitle = "game developer"
    buttonText = "Read more"

  # Tiles Section
  [params.tiles]
    showcase = [
      "personal_project/fireworks_nuts_and_bolts",
      "personal_project/asterisk_mini",
      "personal_project/sound_modeling",
      "school_project/project_sulphur",
      "school_project/agr",
      "school_project/arboreal",
      "school_project/mayor",
      "school_project/barock_battles",
      "personal_project/jellyventure"
    ]

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "f/xoqyzlbg"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Maarten ten Velden"

    [[params.footer.social]]
      icon = "fa-envelope"
      url = "mailto:info@wallby.nl"
      label = "Email"
      
    [[params.footer.social]]
      icon = "fa-linkedin"
      url = "https://www.linkedin.com/in/maarten-ten-velden/"
      label = "LinkedIn"
            
    [[params.footer.social]]
      icon = "fa-github"
      url = "https://www.github.com/Wallby"
      label = "GitHub"
    
    [[params.footer.social]]
      icon = "fa-gitlab"
      url = "https://www.gitlab.com/Wallby"
      label = "GitLab"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
