# Site settings
baseURL = "http://www.maartentenvelden.nl"
languageCode = "en-us"
title = "Maarten ten Velden"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Maarten ten Velden"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Portfolio"
    subtitle = "of Maarten ten Velden"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blog"
      url = "blogs"

    [[params.navigation.links]]
      name = "About me"
      url = "page/about"

    [[params.navigation.button1]]
      name = "What I can do"
      url = "projects"

    [[params.navigation.button2]]
      name = "Download my CV"
      url = "cv.pdf"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Maarten"
    subtitle = "A passionate real-time application programmer, also a great cook"
    buttonText = "Read more"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Project Sulphur"
      subtitle = "A cross-platform custom engine written in C++"
      image = "project_sulphur.jpg"
      url = "projects/project_sulphur"

    [[params.tiles.showcase]]
      title = "AGR"
      subtitle = "A cross-platform racing game and engine written in C++"
      image = "agr.png"
      url = "projects/agr"

    [[params.tiles.showcase]]
      title = "Mayor"
      subtitle = "An atmospheric city management game made in two weeks"
      image = "mayor.jpg"
      url = "projects/mayor"

    [[params.tiles.showcase]]
      title = "Halo Hunters"
      subtitle = "A fast-paced flight combat game made in two weeks"
      image = "halo_hunters.png"
      url = "projects/halo_hunters"

    [[params.tiles.showcase]]
      title = "BaRock Battles"
      subtitle = "An award-winning musical arena party game made for the global jam"
      image = "barock_battles.png"
      url = "projects/barock_battles"

    [[params.tiles.showcase]]
      title = "See more..."
      subtitle = "I have tons of personal projects too"
      image = "pic05.jpg"
      url = "projects/voodoo_sweet_revengine"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About me"
    subtitle = """You are looking at the proud achievements of Maarten ten Velden:
    a pragmatic and highly passionate programmer with experience in real-time
    applications written in C++, games development and software development
    methodologies. Programming is my passion, as well is classical and jazz
    piano, guitar, cooking, and a healthy lifestyle through meditation and
    self-inquiry. I am always looking to challenge myself in news ways. One of my
    big beliefs is that learning works through repetitive failure, and sooner
    rather than later."""
    buttonText = "My achievements"
    url = "projects"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "maartentenvelden@hotmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(31) 6 28196052"

    [[params.contact.address]]
    title = "Address"
    street = "Nieuwstraat 40D"
    city = "Breda, 4811 WV"
    country = "Netherlands"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Maarten ten velden"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/Wallby"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"

    [[params.footer.quicklinks]]
      text = "Email me: "
      url= "mailto:maartentenvelden@hotmail.com"
      alt = "maartentenvelden@hotmail.com"
