baseURL = "http://example.org/"
languageCode = "en-us"
title = "Maarten ten Velden"
theme = "beautifulhugo"
#metaDataFormat = "yaml"

[Params]
  subtitle = "A programming enthousiast with a passion for design and mathematics"
  logo = "https://www.gravatar.com/avatar/cc0746c6e20909b347c153a932e0a235?s=512"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false # TODO: Figure out what RSS is
  comments = true

  [Author]
    name = "Maarten"
    website = "#"
    email = "maartentenvelden@hotmail.com"
    github = "Wallby"
    linkedin = "maarten-ten-velden-b4434614a"
    stackoverflow = "users/4825512/maarten-ten-velden"

  # Major sections
  [[menu.main]]
      name = "Home"
      url = ""
      weight = 1

  [[menu.main]]
      identifier = "portfolio"
      name = "Portfolio"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "page/about/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "page/contact/"
      weight = 4

  # Minor sections
  [[menu.main]]
    parent = "portfolio"
    name = "Professional"
    url = "professional/"
    weight = 1

  [[menu.main]]
    parent = "portfolio"
    name = "Educational"
    url = "educational/"
    weight = 2

  [[menu.main]]
    parent = "portfolio"
    name = "Personal"
    url = "personal/"
    weight = 3
